CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(45) NOT NULL, password VARCHAR(45) NOT NULL, first_name VARCHAR(100) NOT NULL, second_name VARCHAR(100), last_name VARCHAR(100) NOT NULL, mother_name VARCHAR(100));

